[package]
name = "archive_thumbnailer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
image = "0.25.2"
log = "0.4.22"
zip = "2.2.0"
